services:
  postgresql:
    image: postgres
    container_name: postgresdb
    restart: unless-stopped
    environment:
      POSTGRES_USER: todo
      POSTGRES_PASSWORD: todo
      POSTGRES_DB: todo
    ports:
      - "5432:5432"
    volumes:
      - todo:/var/lib/postgresql/data

networks:
  todo-network:
    driver: bridge

volumes:
  todo: