
server:
  tomcat:
    relaxed-query-chars: "[,]"

spring:
  application:
    name: todo
  datasource:
    url: jdbc:postgresql://postgres:5432/todo
    username: todo
    password: todo

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  flyway:
    enabled: true
    default-schema: todo
    locations: classpath:/db/migration/postgres
    user: todo
    password: todo
    url: jdbc:postgresql://postgres:5432/todo

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus,metrics
      base-path: /actuator


jwt:
  secret: de04d58dc5ccc4b9671c3627fb8d626fe4a15810bc1fe3e724feea761965fb71
